apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration

profiles:
  - schedulerName: default-scheduler

    plugins:
      filter:
        enabled:
          - name: "NodeResourcesFit"
          - name: "NodeName"
          - name: "NodeUnschedulable"
          - name: "TaintToleration"

      preScore:
        enabled:
          - name: "PowerAware"

      score:
        enabled:
          - name: "PowerAware"
            weight: 1
        disabled:
          - name: "*"   # Disable default scoring to follow pure TOPSIS

    pluginConfig:
      - name: PowerAware
        args:
          kind: PowerAwareArgs
          apiVersion: kubescheduler.config.k8s.io/v1

          # EXACT paper configuration
          podLoadBalancingCriteria:
            weight: 0.2
            type: "Cost"

          cpuCriteria:
            weight: 0.2
            type: "Cost"

          memCriteria:
            weight: 0.2
            type: "Cost"

          powerCriteria:
            weight: 0.4
            type: "Cost"

          powerModel:
            k0: 150.0
            k1: 100.0
            k2: 3.0
