apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
profiles:
  - schedulerName: power-aware-scheduler
    plugins:
      filter:
        enabled:
          - name: "NodeResourcesFit"
          - name: "NodeName"
          - name: "NodeUnschedulable"
          - name: "TaintToleration"
      preScore:
        enabled:
          - name: "PowerAware"
      score:
        disabled:
          - name: "*" 
        enabled:
          - name: "PowerAware"
            weight: 1
    pluginConfig:
      - name: PowerAware
        args:
          podLoadBalancingCriteria:
            weight: 0.2
            type: "Cost"
          cpuCriteria:
            weight: 0.2
            type: "Cost"
          memCriteria:
            weight: 0.2
            type: "Cost"
          powerCriteria:
            weight: 0.4
            type: "Cost"     # Reverted to Cost to avoid Large nodes
          powerModel:
            k0: 10.0          # 5W idle per CPU core
            k1: 5.0         # 10W max dynamic load per CPU core
            k2: 4.0

  - schedulerName: default-scheduler
    plugins:
      filter:
        enabled:
          - name: "NodeResourcesFit"
          - name: "NodeName"
          - name: "NodeUnschedulable"
          - name: "TaintToleration"
      score:
        enabled:
          - name: "NodeResourcesFit"
          - name: "NodeResourcesBalancedAllocation"
          - name: "ImageLocality"
          - name: "TaintToleration"