apiVersion: v1
kind: Node
metadata:
  name: small-node-0
  namespace: default
status:
  allocatable: &id001
    cpu: '4'
    memory: 9Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-1
  namespace: default
status:
  allocatable: &id001
    cpu: '2'
    memory: 12Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-2
  namespace: default
status:
  allocatable: &id001
    cpu: '2'
    memory: 11Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-3
  namespace: default
status:
  allocatable: &id001
    cpu: '2'
    memory: 9Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-4
  namespace: default
status:
  allocatable: &id001
    cpu: '4'
    memory: 16Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-5
  namespace: default
status:
  allocatable: &id001
    cpu: '2'
    memory: 14Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-6
  namespace: default
status:
  allocatable: &id001
    cpu: '2'
    memory: 8Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-7
  namespace: default
status:
  allocatable: &id001
    cpu: '2'
    memory: 11Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-8
  namespace: default
status:
  allocatable: &id001
    cpu: '2'
    memory: 16Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-9
  namespace: default
status:
  allocatable: &id001
    cpu: '4'
    memory: 8Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-0
  namespace: default
status:
  allocatable: &id001
    cpu: '16'
    memory: 44Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-1
  namespace: default
status:
  allocatable: &id001
    cpu: '16'
    memory: 58Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-2
  namespace: default
status:
  allocatable: &id001
    cpu: '11'
    memory: 60Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-3
  namespace: default
status:
  allocatable: &id001
    cpu: '12'
    memory: 32Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-4
  namespace: default
status:
  allocatable: &id001
    cpu: '10'
    memory: 59Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-5
  namespace: default
status:
  allocatable: &id001
    cpu: '13'
    memory: 49Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-6
  namespace: default
status:
  allocatable: &id001
    cpu: '10'
    memory: 45Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-7
  namespace: default
status:
  allocatable: &id001
    cpu: '13'
    memory: 38Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-8
  namespace: default
status:
  allocatable: &id001
    cpu: '9'
    memory: 56Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-9
  namespace: default
status:
  allocatable: &id001
    cpu: '9'
    memory: 54Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-0
  namespace: default
status:
  allocatable: &id001
    cpu: '54'
    memory: 195Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-1
  namespace: default
status:
  allocatable: &id001
    cpu: '34'
    memory: 245Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-2
  namespace: default
status:
  allocatable: &id001
    cpu: '39'
    memory: 224Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-3
  namespace: default
status:
  allocatable: &id001
    cpu: '37'
    memory: 203Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-4
  namespace: default
status:
  allocatable: &id001
    cpu: '55'
    memory: 177Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-5
  namespace: default
status:
  allocatable: &id001
    cpu: '36'
    memory: 139Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-6
  namespace: default
status:
  allocatable: &id001
    cpu: '46'
    memory: 202Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-7
  namespace: default
status:
  allocatable: &id001
    cpu: '37'
    memory: 187Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-8
  namespace: default
status:
  allocatable: &id001
    cpu: '38'
    memory: 225Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-9
  namespace: default
status:
  allocatable: &id001
    cpu: '49'
    memory: 244Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
