apiVersion: v1
kind: Node
metadata:
  name: small-node-0
  namespace: default
status:
  allocatable: &id001
    cpu: '4'
    memory: 9Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: small-node-1
  namespace: default
status:
  allocatable: &id001
    cpu: '2'
    memory: 12Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-0
  namespace: default
status:
  allocatable: &id001
    cpu: '11'
    memory: 46Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-1
  namespace: default
status:
  allocatable: &id001
    cpu: '10'
    memory: 38Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-2
  namespace: default
status:
  allocatable: &id001
    cpu: '16'
    memory: 37Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: medium-node-3
  namespace: default
status:
  allocatable: &id001
    cpu: '14'
    memory: 34Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-0
  namespace: default
status:
  allocatable: &id001
    cpu: '33'
    memory: 151Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-1
  namespace: default
status:
  allocatable: &id001
    cpu: '45'
    memory: 187Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-2
  namespace: default
status:
  allocatable: &id001
    cpu: '64'
    memory: 134Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
---
apiVersion: v1
kind: Node
metadata:
  name: large-node-3
  namespace: default
status:
  allocatable: &id001
    cpu: '44'
    memory: 235Gi
    pods: '110'
  capacity: *id001
  conditions:
  - status: 'True'
    type: Ready
