apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-0
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1140m
        memory: 4198Mi
      requests:
        cpu: 1140m
        memory: 4198Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-1
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1240m
        memory: 5099Mi
      requests:
        cpu: 1240m
        memory: 5099Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-2
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 720m
        memory: 4515Mi
      requests:
        cpu: 720m
        memory: 4515Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-3
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1180m
        memory: 4452Mi
      requests:
        cpu: 1180m
        memory: 4452Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-4
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1090m
        memory: 4226Mi
      requests:
        cpu: 1090m
        memory: 4226Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-5
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 530m
        memory: 4991Mi
      requests:
        cpu: 530m
        memory: 4991Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-6
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 730m
        memory: 4204Mi
      requests:
        cpu: 730m
        memory: 4204Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-7
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1060m
        memory: 5814Mi
      requests:
        cpu: 1060m
        memory: 5814Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-8
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 720m
        memory: 5235Mi
      requests:
        cpu: 720m
        memory: 5235Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-9
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1310m
        memory: 4122Mi
      requests:
        cpu: 1310m
        memory: 4122Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-10
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1260m
        memory: 4749Mi
      requests:
        cpu: 1260m
        memory: 4749Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-11
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1200m
        memory: 5489Mi
      requests:
        cpu: 1200m
        memory: 5489Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-12
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 780m
        memory: 4977Mi
      requests:
        cpu: 780m
        memory: 4977Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-13
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1460m
        memory: 5474Mi
      requests:
        cpu: 1460m
        memory: 5474Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-14
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 600m
        memory: 5652Mi
      requests:
        cpu: 600m
        memory: 5652Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-15
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 600m
        memory: 5504Mi
      requests:
        cpu: 600m
        memory: 5504Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-16
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1100m
        memory: 4273Mi
      requests:
        cpu: 1100m
        memory: 4273Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-17
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1230m
        memory: 4607Mi
      requests:
        cpu: 1230m
        memory: 4607Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-18
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1470m
        memory: 5646Mi
      requests:
        cpu: 1470m
        memory: 5646Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-19
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 580m
        memory: 5296Mi
      requests:
        cpu: 580m
        memory: 5296Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-20
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1330m
        memory: 5577Mi
      requests:
        cpu: 1330m
        memory: 5577Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-21
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1080m
        memory: 4380Mi
      requests:
        cpu: 1080m
        memory: 4380Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-22
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 550m
        memory: 5029Mi
      requests:
        cpu: 550m
        memory: 5029Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-23
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1270m
        memory: 4422Mi
      requests:
        cpu: 1270m
        memory: 4422Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-24
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1360m
        memory: 4509Mi
      requests:
        cpu: 1360m
        memory: 4509Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-25
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 880m
        memory: 5953Mi
      requests:
        cpu: 880m
        memory: 5953Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-26
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1140m
        memory: 5590Mi
      requests:
        cpu: 1140m
        memory: 5590Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-27
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 660m
        memory: 5551Mi
      requests:
        cpu: 660m
        memory: 5551Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-28
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 710m
        memory: 5189Mi
      requests:
        cpu: 710m
        memory: 5189Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-29
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1200m
        memory: 4388Mi
      requests:
        cpu: 1200m
        memory: 4388Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-30
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1110m
        memory: 4796Mi
      requests:
        cpu: 1110m
        memory: 4796Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-31
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1030m
        memory: 5098Mi
      requests:
        cpu: 1030m
        memory: 5098Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-32
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 660m
        memory: 5650Mi
      requests:
        cpu: 660m
        memory: 5650Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-33
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 770m
        memory: 4995Mi
      requests:
        cpu: 770m
        memory: 4995Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-34
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1180m
        memory: 4325Mi
      requests:
        cpu: 1180m
        memory: 4325Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-35
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 730m
        memory: 4227Mi
      requests:
        cpu: 730m
        memory: 4227Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-36
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1310m
        memory: 5739Mi
      requests:
        cpu: 1310m
        memory: 5739Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-37
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 770m
        memory: 4960Mi
      requests:
        cpu: 770m
        memory: 4960Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-38
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1410m
        memory: 5384Mi
      requests:
        cpu: 1410m
        memory: 5384Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-39
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 710m
        memory: 6140Mi
      requests:
        cpu: 710m
        memory: 6140Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-40
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 900m
        memory: 5975Mi
      requests:
        cpu: 900m
        memory: 5975Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-41
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 640m
        memory: 4667Mi
      requests:
        cpu: 640m
        memory: 4667Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-42
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 750m
        memory: 5172Mi
      requests:
        cpu: 750m
        memory: 5172Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-43
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1250m
        memory: 5850Mi
      requests:
        cpu: 1250m
        memory: 5850Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-44
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1400m
        memory: 5731Mi
      requests:
        cpu: 1400m
        memory: 5731Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-45
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 860m
        memory: 4662Mi
      requests:
        cpu: 860m
        memory: 4662Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-46
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1010m
        memory: 4468Mi
      requests:
        cpu: 1010m
        memory: 4468Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-47
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1260m
        memory: 4545Mi
      requests:
        cpu: 1260m
        memory: 4545Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-48
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 650m
        memory: 4751Mi
      requests:
        cpu: 650m
        memory: 4751Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-49
  namespace: default
spec:
  containers:
  - image: nginx:stable-alpine
    name: workload
    resources:
      limits:
        cpu: 1290m
        memory: 5825Mi
      requests:
        cpu: 1290m
        memory: 5825Mi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
