apiVersion: v1
kind: Pod
metadata:
  name: test-b2-0
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-1
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-2
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-3
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-4
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-5
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-6
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-7
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-8
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-9
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-10
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-11
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-12
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-13
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-14
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-15
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-16
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-17
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-18
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-19
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-20
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-21
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-22
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-23
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-24
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-25
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-26
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-27
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-28
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-29
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-30
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-31
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-32
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-33
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-34
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-35
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-36
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-37
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-38
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: test-b2-39
spec:
  containers:
  - image: nginx:alpine
    name: c
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
  restartPolicy: Never
  schedulerName: power-aware-scheduler
