apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Node
  metadata:
    name: worker-0
  status:
    capacity: {cpu: "4", memory: "8Gi", pods: "20"}
    allocatable: {cpu: "4", memory: "8Gi", pods: "20"}
- apiVersion: v1
  kind: Node
  metadata:
    name: worker-1
  status:
    capacity: {cpu: "4", memory: "8Gi", pods: "20"}
    allocatable: {cpu: "4", memory: "8Gi", pods: "20"}
- apiVersion: v1
  kind: Node
  metadata:
    name: worker-2
  status:
    capacity: {cpu: "4", memory: "8Gi", pods: "20"}
    allocatable: {cpu: "4", memory: "8Gi", pods: "20"}
- apiVersion: v1
  kind: Node
  metadata:
    name: worker-3
  status:
    capacity: {cpu: "4", memory: "8Gi", pods: "20"}
    allocatable: {cpu: "4", memory: "8Gi", pods: "20"}